# Generated by Django 5.0.1 on 2025-01-08 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_farmer_product_createdat_product_updatedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_name', to='api.farmer'),
        ),
    ]
